### PR TITLE
Deprecate this module

### PR DESCRIPTION
**Pull request by i-like-robots**
CC https://github.com/Financial-Times/n-ui/pull/71

### CODE REVIEW

**Comment by ironsidevsquincy** [comment]
Could we just add a deprecation notice but not delete the code? Had issues yesterday were something was still using `next-buttons` and a dependency needed updating but the repo had been deleted

**Comment by i-like-robots** [comment]
How about I create an empty deprecated branch and make that the default public view?

**Comment by ironsidevsquincy** [comment]
Good idea

**Comment by i-like-robots** [comment]
Done and done, sorry about that!

**Pull request merged**
