### PR TITLE
Remove vue

### PR DESCRIPTION
**Pull request by commuterjoy**
Large frameworks inside small components need more discussion with wider group.

### CODE REVIEW

**Comment by matthew-andrews** [comment]
what's the before and after compiled file size difference?

**Comment by commuterjoy** [comment]
Nothing :)

It's being used over here too https://github.com/Financial-Times/n-corporate-overlay

But if I chop that out ...

```
-rw-r--r--   1 matt.chadburn  FTROOT\Domain Users  1405144 23 Dec 08:41 main-after-vue
-rw-r--r--   1 matt.chadburn  FTROOT\Domain Users  1657593 23 Dec 08:34 main-before-vue
```

gzip...

```
-rw-r--r--   1 matt.chadburn  FTROOT\Domain Users  322565 23 Dec 08:41 main-after-vue.gz
-rw-r--r--   1 matt.chadburn  FTROOT\Domain Users  392261 23 Dec 08:34 main-before-vue.gz
```

**Comment by matthew-andrews** [comment]
^^ nice

**Comment by adgad** [comment]
:+1: Amusingly even the code is almost 20 lines fewer without a framework

**Pull request merged**
